name: Test
on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  javascript-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Install
        run: npm ci --dev
      - name: Check
        run: npm run check
      - name: Lint
        run: npm run lint
